server:
  port: 8081
  servlet:
    context-path: /web-admin
spring:
  datasource:
    url: jdbc:mysql://123.56.47.145:3306/shopdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: Root123456.
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.aaa.admin.domain.model