server:
  port: 8081
  servlet:
    context-path: /web-admin
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shopdb?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.admin.domain.model
pagehelper:
  helper-dialect: mysql
  params: count=countSql